# config/application.example.yml

# Using the figaro command, you can set values:
# figaro heroku:set -e production -a annapurna-development
# figaro heroku:set -e production -a annapurna-staging
# figaro heroku:set -e production -a annapurna-production

# For more information:
# figaro help heroku:set

# Add configuration values here, as shown below.

# S3 [https://aws.amazon.com/s3/]
# config/initializers/carrierwave.rb
STORAGE_REGION: "xxxxxxxx"
STORAGE_ACCESS_KEY_ID: "xxxxxxxxxxxxxxxxxxxxxx"
STORAGE_SECRET_ACCESS_KEY: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Mailgun [https://www.mailgun.com/]
# config/initializers/transactional_email.rb
TE_DOMAIN: "xxxxxxxxxxxxxxxxxxxxxx"
TE_USER_NAME: "xxxxxxxxxxxxxxxxxxxxxx"
TE_PASSWORD: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

#################################################################

default: &default
  APP_NAME: "Annapurna"
  TIME_ZONE: "London"
  COOKIE_SESSION: "_annapurna_session"

# You can generate a new secret key by running the following shell command: "rake secret"
test:
  <<: *default
  DATABASE_NAME: "annapurna_test"
  SECRET_KEY_BASE: "820785efcb4c498f51264e0bbc1b721501dcf65dbfdb9cbafca17e5ffd59bc5314d3d254a2646fc9925e041edc80e0d20bd1bbf0dbcb6515c30350922366cd28"

development:
  <<: *default
  DATABASE_NAME: "annapurna_development"
  SECRET_KEY_BASE: "6471adef417db2b193f69488e62a6f1d0668dcae32705d686fe49c1fc573622f54f013faa593f83d7540321515e5768365bdc63278989c7ce555f4cdb25b3173"

production:
  <<: *default
  LANG: "en_GB.UTF-8"
